// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlGWC4SLhEiPx8YsdMZZ67Hnt_Q6p1WzA',
    appId: '1:454959884733:web:54797c64b2fa4a700a4ad4',
    messagingSenderId: '454959884733',
    projectId: 'campusconnect-1f143',
    authDomain: 'campusconnect-1f143.firebaseapp.com',
    storageBucket: 'campusconnect-1f143.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvLw8NhNuTp-gU9zdagSOLZsEIrh2TyrQ',
    appId: '1:454959884733:android:35139d6dd3bebbd40a4ad4',
    messagingSenderId: '454959884733',
    projectId: 'campusconnect-1f143',
    storageBucket: 'campusconnect-1f143.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB8CHaoEnfzSe_SzsEB3uSaFtrwibUBSg',
    appId: '1:454959884733:ios:833fee302e88d4d50a4ad4',
    messagingSenderId: '454959884733',
    projectId: 'campusconnect-1f143',
    storageBucket: 'campusconnect-1f143.firebasestorage.app',
    iosBundleId: 'com.example.campusConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBB8CHaoEnfzSe_SzsEB3uSaFtrwibUBSg',
    appId: '1:454959884733:ios:833fee302e88d4d50a4ad4',
    messagingSenderId: '454959884733',
    projectId: 'campusconnect-1f143',
    storageBucket: 'campusconnect-1f143.firebasestorage.app',
    iosBundleId: 'com.example.campusConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlGWC4SLhEiPx8YsdMZZ67Hnt_Q6p1WzA',
    appId: '1:454959884733:web:f049f5af688d2a520a4ad4',
    messagingSenderId: '454959884733',
    projectId: 'campusconnect-1f143',
    authDomain: 'campusconnect-1f143.firebaseapp.com',
    storageBucket: 'campusconnect-1f143.firebasestorage.app',
  );

}